//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empresa.InfraData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        public long IdFactura { get; set; }
        public string NroFactura { get; set; }
        public Nullable<decimal> Pago { get; set; }
        public Nullable<long> IdOrdenServicio { get; set; }
    
        public virtual OrdenServicio OrdenServicio { get; set; }
    }
}
