//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empresa.InfraData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenServicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenServicio()
        {
            this.Facturas = new HashSet<Facturas>();
            this.Resultados = new HashSet<Resultados>();
            this.OrdenServicioDetalle = new HashSet<OrdenServicioDetalle>();
        }
    
        public long IdOrdenServicio { get; set; }
        public Nullable<long> IdPaciente { get; set; }
        public Nullable<long> IdAseguradora { get; set; }
        public Nullable<long> IdExamen { get; set; }
        public Nullable<int> NroRegistro { get; set; }
        public string IngresoPor { get; set; }
        public Nullable<int> IdMedico { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public Nullable<System.DateTime> FechaRecepcion { get; set; }
    
        public virtual Aseguradoras Aseguradoras { get; set; }
        public virtual Examenes Examenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas> Facturas { get; set; }
        public virtual Pacientes Pacientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resultados> Resultados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenServicioDetalle> OrdenServicioDetalle { get; set; }
    }
}
