//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empresa.InfraData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pacientes()
        {
            this.OrdenServicio = new HashSet<OrdenServicio>();
        }
    
        public long IdPaciente { get; set; }
        public Nullable<long> IdMedico { get; set; }
        public Nullable<long> IdExamen { get; set; }
        public Nullable<int> NroIdentificacionPaciente { get; set; }
        public string Nombres { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public Nullable<int> Sexo { get; set; }
        public string Hclinica { get; set; }
        public string FechaNacimiento { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> Telefono { get; set; }
    
        public virtual Medicos Medicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenServicio> OrdenServicio { get; set; }
    }
}
