//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empresa.InfraData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pruebas
    {
        public long IdPrueba { get; set; }
        public Nullable<long> IdExamen { get; set; }
        public string NombrePrueba { get; set; }
        public Nullable<long> IdValorReferencia { get; set; }
    
        public virtual Examenes Examenes { get; set; }
        public virtual ValoresReferencia ValoresReferencia { get; set; }
    }
}
