//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empresa.InfraData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultadosDetalle
    {
        public long IdResultadoDetalle { get; set; }
        public Nullable<long> IdResultado { get; set; }
        public Nullable<long> IdExamen { get; set; }
        public Nullable<long> IdPrueba { get; set; }
        public Nullable<long> IdValorReferencia { get; set; }
        public string ValorResultado { get; set; }
    
        public virtual Resultados Resultados { get; set; }
    }
}
