//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empresa.InfraData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resultados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resultados()
        {
            this.ResultadosDetalle = new HashSet<ResultadosDetalle>();
        }
    
        public long IdResultado { get; set; }
        public Nullable<long> IdRegistro { get; set; }
        public Nullable<long> IdLaboratorista { get; set; }
        public Nullable<long> IdExamen { get; set; }
    
        public virtual Examenes Examenes { get; set; }
        public virtual Laboratoristas Laboratoristas { get; set; }
        public virtual OrdenServicio OrdenServicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultadosDetalle> ResultadosDetalle { get; set; }
    }
}
