//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empresa.InfraData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValoresReferencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ValoresReferencia()
        {
            this.Pruebas = new HashSet<Pruebas>();
        }
    
        public long IdValorReferencia { get; set; }
        public Nullable<decimal> LimiteInferiorEdad { get; set; }
        public Nullable<decimal> LimiteSuperiorEdad { get; set; }
        public Nullable<decimal> LimiteInferiorSexo { get; set; }
        public Nullable<decimal> LimiteSuperiorSexo { get; set; }
        public string unidad { get; set; }
        public string TipoValor1 { get; set; }
        public string TipoValor2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pruebas> Pruebas { get; set; }
    }
}
